#!/bin/bash


echo Content-type: text/html
echo

rm -f ../values 
rm -f values
rm -f columns.g
rm -f columnPlacer.sh
touch values
touch columnPlacer.sh

echo `$QUERY_STRING`
i=1
while [ $i -le 47 ]
do

echo $QUERY_STRING | cut -d"&" -f$i | cut -d"=" -f2 >> values

i=$(( $i + 1 ))

done

./watertank < values
chmod 777 columnPlacer.sh
./columnPlacer.sh &>/dev/null
./render.sh 
echo "<center>
	<table>
	<tr><td><img src='../../../../cgi-images/wtrt.png'></td>
	<td><img src='../../../../cgi-images/wtrt_front.png'></td></tr>
	<tr><td><img src='../../../../cgi-images/wtrt_top.png'></td></tr>
	</table>
	</center>"
