#!/bin/bash


echo Content-type: text/html
echo

rm -f ../values
rm -f values

touch values

echo `$QUERY_STRING`
i=1
while [ $i -le 47 ]
do

echo $QUERY_STRING | cut -d"&" -f$i | cut -d"=" -f2 >> values

i=$(( $i + 1 ))

done

chmod 777 values
cp values ../

echo "Processing...."
echo "<meta http-equiv=\"refresh\" content=\"1;url=../values\">"

